name: image crawl

# on 触发条件
on:
  # 定时触发
  schedule:
    # UTC时间与北京时间8小时时差
    # UTC时间 18点执行一次，即UTC+8北京时间 2点执行一次
    - cron:  '0 18 * * *'
  # 监听 git push 到指定分支时触发
  push:
    branches:
      - main
  # 人工触发
  workflow_dispatch:
  
env:
  # 需要用到本地时间
  TZ: Asia/Shanghai

jobs:
  build:
    # 指定执行系统环境
    runs-on: ubuntu-latest
    permissions:
      # 为这个 Job 新增了写权限
      contents: write
    # 执行的步骤
    steps:
      # 拉取分支代码
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      # 安装 Python 环境 
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: 'x64'
      # 爬取壁纸
      - name: crawl bing image
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com; fi
          python image.py
      # 提交文件
      - name: commit files
        run: |
          git config --local user.name 'Github Action'
          git config --local user.email 'github-actions@github.com'
          git add .
          git commit -m "$(git config user.name) Auto Update At `TZ=UTC-8 date +%Y-%m-%d\ %H:%M:%S`"
          git push
